sprint-2/step-2/attempt-1
antondrob/react-burger pull request #5
Opened 2021-08-14 12:40 UTC by antondrob

2021-08-14 15:10 UTC, SmilingJey requested changes
Здравствуйте!

Хорошая работа, приложение почти полностью соответсвует макету, стейт перенесен в redux, правильно работает добавление ингредиентов перетаскиванием

Но есть несколько замечаний:

**Замечания которые необходимо исправить:**

- при клике на таб он не становится активным

- отсутствие данных в сторе обозначайте как null, а не пустой объект, не нужны будут проверки на содержимое объекта

- поместите каждый редьюсер в отдельный файл, не нужно описывать все в одном файле, аналогично нужно разнести и экшены

- в редьюсере нельзя генерировать id

**Более мелкие замечания и места, в которых можно улучшить проект так же отмечены в коде:**

2021-08-14 15:10 UTC, SmilingJey commented on src/services/preloadedState.js
> +    ingredient: {},
**Надо исправить**

отсутствие  данных обозначайте как null, а не пустой объект

```
ingredient: {},
```

Это поможет избавиться от лишних проверок в App ` Object.keys(ingredient).length > 0 && ingredient.constructor === Object`

```
{ingredient && (
      <Modal>
             <IngredientDetails details={ingredient}/>
      </Modal>
)}
```

2021-08-14 15:10 UTC, SmilingJey commented on src/services/preloadedState.js
> +        data: {},
**Надо исправить**

отсутствие данных обозначайте как null, а не пустой объект

2021-08-14 15:10 UTC, SmilingJey commented on src/services/preloadedState.js
> +        bun: {},
**Надо исправить**

отсутствие данных обозначайте как null, а не пустой объект

2021-08-14 15:10 UTC, SmilingJey commented on js/components/app-header/AppHeader.js
> +                    <a href="/" className={headerStyles.menuItemActive}>
**Можно лучше**

пунктирная обводка у кнопок

![2021-08-14_17-33-29](https://user-images.githubusercontent.com/9317133/129449793-f38a52ea-caaf-4e76-a1d9-858ad4b3b60d.png)


 нужна, что бы только показать на макете размер ссылок, её не должно быть в итоговом отображении

2021-08-14 15:10 UTC, SmilingJey commented on src/components/burger-constructor/BurgerConstructor.js
> +    const orderTotal = notBun.reduce(function (acc, obj) {
**Можно лучше**

рассчtт лучше обернуть в useMemo


```
const totalPrice = useMemo(()=> {
   return **рассчет стоимости**
}, [notBun, bun])
```

так стоимость будет перерасчитываться в момент изменения бургера

2021-08-14 15:10 UTC, SmilingJey commented on src/components/burger-constructor/BurgerConstructor.js
> +                                    price={bun.price / 100}
**Можно лучше**

не нашел нигде в задании, где было бы сказано, что цену нужно делить на 100, отображайте как есть

2021-08-14 15:10 UTC, SmilingJey commented on src/components/burger-ingredients/BurgerIngredients.js
> +    const tabs = useSelector(store => store.tabs);
**Можно лучше**

состояние табов не нужно выносить в стор, это локальное состояние одного конкретного компонента, которое не обязательно восстанавливать при размонтировании компонента, можно описать стейт просто здесь

2021-08-14 15:10 UTC, SmilingJey commented on src/components/burger-ingredients/BurgerIngredients.js
**Можно лучше**
при клике на соответвующий таб должен происходить скрол к нужному разделй в списке, а таб должен стать активным

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:
```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };
```
где заголовкам разделов заданы соответсвующие атрибуты id 

https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2021-08-14 15:10 UTC, SmilingJey commented on js/components/ingredient-details/IngredientDetails.js
> +IngredientDetails.propTypes = {
**Можно лучше**
во многих компонентах дублируется описание PropTypes ингредиента
Лучше вынести его в отдельный файл (можно создать файл prop-types.js в корне src ) и переиспользовать описание пропсов ингрединта, а не дублировать

2021-08-14 15:10 UTC, SmilingJey commented on js/components/modal/Modal.js
> +            if (event.keyCode === 27) {
**Надо исправить**

вынесите магическое значение 27 в именованную константу `ESC_KEYCODE`

2021-08-14 15:10 UTC, SmilingJey commented on src/components/sortable-ingredient/SortableIngredient.js
> +            <DragIcon/>
**Можно лучше**

по макету ширина ингредиентов такая же как и ширина булок, а иконка перетаскивания снаружи

![2021-08-14_17-47-34](https://user-images.githubusercontent.com/9317133/129450187-91ee98cf-0d8d-4dd2-94c9-9d29aedd891e.png)

2021-08-14 15:10 UTC, SmilingJey commented on src/services/actions/index.js
> +
**Надо исправить**

Приложение со временем будет разрастаться и будут добавляться все новые экшены, плохо, если этот файл будет постоянно разрастаться

Вынесите группу экшенов обрабатывающие данные одной предметной области (одного "домена")  в отдельный файл

Например:
- экшены загрузки ингредиентов (ingredients.js)
- экшены попапов  (ingredient-popup.js)
- экшены конструктора (constructor.js)
- экшены оформления заказа (order.js)

2021-08-14 15:10 UTC, SmilingJey commented on src/services/actions/index.js
> +            .then(res => res.json())
**Можно лучше**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2021-08-14 15:10 UTC, SmilingJey commented on src/services/actions/index.js
> +        fetch(API_URL)
**Можно лучше**

следует делать return промиса, что нам поможет при тестировании в следующем спринте и при необходимости можно будет продолжить цепочку в компоненте и совершить дествие после выполнения запроса

т.е. должно быть:
```
export const getIngredients = () => (dispatch) => {
	dispatch({ type: GET_INGREDIENTS_REQUEST });

	return fetch(API_URL)   //return  промиса
        .................
```

проверьте и других похожих местах

2021-08-14 15:10 UTC, SmilingJey commented on src/services/reducers/allReducers.js
> +// Редьюсер списка ингредиентов
**Надо исправить**

поместите каждый редьюсер в отдельный файл, не нужно описывать все в одном файле

2021-08-14 15:10 UTC, SmilingJey commented on src/services/reducers/allReducers.js
> +                        uniqueId: action.item._id + uuid()
**Надо исправить**

редюсер должен быть чистой функцией, чистая функция при каждом вызове дает одинаковый результат. А сейчас в редьюсере каждый раз будет новый случайны id генерироваться.
Поэтому нельзя генерировать id в редьюсере, нужно что бы id приходил в экшене в payload и использовать тот

2021-08-14 15:10 UTC, SmilingJey commented on src/services/reducers/allReducers.js
> +export const ingredientTabsReducer = (state = preloadedState.tabs, action) => {
**Можно лучше**

состояние активного таба лучше оставить просто в стейте компонента

2021-08-14 15:10 UTC, SmilingJey commented on src/services/uuid.js
> +export function uuid() {
**Можно лучше**

используйте библиотеку https://www.npmjs.com/package/uuid

2021-08-14 15:10 UTC, SmilingJey commented on src/index.jsx
> +const store = configureStore({
**Можно лучше**

перенесите конфигурацию стора в файл services/store.js и экспортируйте созданный стор из него

2021-08-14 15:10 UTC, SmilingJey commented on src/index.jsx
> +    middleware: [thunk],
**Можно лучше**

configureStore по умолчанию добавляет thunk , если не указывать

2021-08-15 17:48 UTC, SmilingJey approved these changes
Отлично, замечания исправлены, но не забудьте поправить два отмеченных замечания, иначе сейчас приложение падает с ошибкой

Успехов в дальнейшем обучении!

2021-08-15 17:48 UTC, SmilingJey commented on src/services/actions/order.js
> +        .then(checkReponse())
**Надо исправить**

уберите скобки, нужно передать функцию, а не вызвать её

`.then(checkReponse)`

иначе приложение падает с ошибкой

2021-08-15 17:48 UTC, SmilingJey commented on src/services/actions/ingredients.js
> +        .then(checkReponse())
**Надо исправить**

уберите скобки, нужно передать функцию, а не вызвать её

`.then(checkReponse)`

иначе приложение падает с ошибкой

2021-08-15 20:38 UTC, antondrob commented on src/services/actions/order.js
> +        .then(checkReponse())
Да, точно. Не очень понимаю правда, как это работает. Почему именно не вызывать нужно, а просто передать ее название? Где можно почитать об этом?

2021-08-15 20:40 UTC, SmilingJey commented on src/services/actions/order.js
> +        .then(checkReponse())
затрудняюсь дать хорошую ссылку, но попробуйте разобраться с работой промисов https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise   - в then нужно передавать функцию, а не её вызов

2021-08-15 20:47 UTC, merged